### ISSUE TITLE
Compressed xex (Minecraft) fails to open

### ISSUE THREAD

**Issue by Margen67** [zeroKilo/XEXLoaderWV#21]
Compressed xex like Minecraft fail to open unless I remove the compression using xextool:
![image](https://github.com/zeroKilo/XEXLoaderWV/assets/3462541/d7e90568-fd82-4bea-be61-7b666a5831ad)

**Comment by syndiate** [comment]
If anyone else is having trouble with this, run this command: `xextool -e d -c u default.xex`
 To unencrypt and uncompress the xex file for usage with Ghidra
 @zeroKilo I know you can run executable files in a Java program, but can you run them in a Ghidra extension? If so, you may want to add xextool commands and such like the one I put above.

**Comment by zeroKilo** [comment]
well to be honest I rather implement the proper loading myself, im just low on time. my whole plugin is essentially an open source version of a tool like xextool just not for converting but loading into ghidra. if you can send me an example xex file that fail then I have something to work with. all my xex files work sofar

**Comment by syndiate** [comment]
@zeroKilo By an xex file that fails do you mean that's already unencrypted and uncompressed?

**Comment by zeroKilo** [comment]
Any that fails to get loaded by my plugin, very simply

**Comment by syndiate** [comment]
@zeroKilo https://archive.org/details/minecraft-xbox-360-edition-base-game
Download this XBLA file, extract default.xex from it, and put it through your tool, it fails because the xex is encrypted and compressed

**Comment by zeroKilo** [comment]
alright, I will take a look this week hopefully (very busy atm)

**Comment by zeroKilo** [comment]
alright, this took me a while to find but it was a simple signed/unsigned problem, so I fixed the bug and it can load the xex file now.

https://github.com/zeroKilo/XEXLoaderWV/commit/7b2f7d46dd2d29bda50f708cf9a8576aafd88291

https://github.com/zeroKilo/XEXLoaderWV/releases/tag/11.1.1

please close this ticket if you have no further problems with loading xex files

**Comment by avachon100510** [comment]
I am attempting to open the .xexp file, but I get this error:
![image](https://github.com/zeroKilo/XEXLoaderWV/assets/96546431/344eead9-8163-4490-8d14-0c089d643e59)

**Comment by avachon100510** [comment]
Okay, never mind, clearly I did something wrong on my end.

**Comment by avachon100510** [comment]
God damn it, the error still occurs even if I uncompressed and uncrypted the .xex file with XeXTool 6.3...
![image](https://github.com/zeroKilo/XEXLoaderWV/assets/96546431/4a795730-32dd-4e3d-900c-59a1251857ba)

**Comment by zeroKilo** [comment]
yeah, tell me some xex doesnt work but dont ever link it, so I could possibly fix anything. did you even use the new release?

**Comment by avachon100510** [comment]
Well, it looks like I did something wrong indeed. It works as intended now, it was me who did an oopsie. Yes, I did use the new release.
